name: Hello
on: push
jobs:
  job1-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world1!"
      - uses: actions/checkout@v4

  job2-hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -la
          tree -a .
          echo "Hello, world2!"
      - uses: actions/checkout@v4
      - run: |
          ls -la
          tree -a .
          echo "Hello, world4!"
